version: '3.8'
services:
  jenkins:
    build:
      dockerfile: DockerfileJenkins
      context: .
    privileged: true
    restart: always
    user: root
    ports:
      - 9080:8080
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.m2:/root/.m2

